#!/bin/sh
set -ev

if [ -z "$MARATHON_APP_ID" ]; then
  echo "Not compiling j2 config file because this is not running in Marathon!"
else
  /bin/env_parse ${SERVER_CONFIG}.j2
  export CONFIG_LINE="-Dconfig.file=${SERVER_CONFIG}"  
fi

su socrata -c '/usr/bin/java \
    $CONFIG_LINE \
    -cp $SERVER_ARTIFACT \
    com.socrata.soda.server.MigrateSchema migrate'

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    $CONFIG_LINE \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -jar $SERVER_ARTIFACT'
