#!/bin/sh
set -ev

/bin/env_parse ${SERVER_CONFIG}.j2

su socrata -c '/usr/bin/java \
    -Dconfig.file=${SERVER_CONFIG} \
    -cp $SERVER_ARTIFACT \
    com.socrata.soda.server.MigrateSchema migrate'

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -jar $SERVER_ARTIFACT'
