#!/bin/sh
set -ev

if [ -n "$ECS_CONTAINER_METADATA_URI_V4" ]; then
    ARK_HOST="$(curl -sf "$ECS_CONTAINER_METADATA_URI_V4" | jq -r '.Networks[0].IPv4Addresses[0]')"
    export ARK_HOST
fi

if [ -z "$MARATHON_APP_ID" ] && [ -z "$ECS_CONTAINER_METADATA_URI_V4" ]; then
  echo "Not compiling j2 config file because this is not running in Marathon!"
else
  /bin/env_parse ${SERVER_CONFIG}.j2
fi

echo "Using config $SERVER_CONFIG"

su socrata -c '/usr/bin/java \
    -Dconfig.file=${SERVER_CONFIG} \
    -cp $SERVER_ARTIFACT \
    com.socrata.soda.server.MigrateSchema migrate'

exec su socrata -c 'exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    ${JAVA_GC_LOG_BEHAVIOR} \
    -jar $SERVER_ARTIFACT'
